export const restaurantData = [
    {
        id: 1,
        name: "Italian Food Service",
        img: [
            "https://www.sortiraparis.com/images/80/91874/582754-photos-le-cafe-de-l-homme.jpg",
            "https://vistapointe.net/images/restaurant-3.jpg",
            "https://www.shilla.net/images/contents/dining/FRC/R00000019XVP_EN.jpg",
            "https://cdn.vox-cdn.com/thumbor/wuDWh1y6HHfzTUtYBPKAzBU4wTk=/0x0:1920x1280/1200x900/filters:focal(807x487:1113x793)/cdn.vox-cdn.com/uploads/chorus_image/image/58248869/Sooki_and_Mimi_Bar_and_room_cr_Jes_Lahay.97.jpg",
            "https://images.unsplash.com/photo-1552566626-52f8b828add9?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8N3x8cmVzdGF1cmFudHxlbnwwfHwwfHw%3D&w=1000&q=80",
        ],
        location: "123654 78546",
        street: "Saryan 4/2",
        country: "Armenia",
        city: "Yerevan",
        contact: {
            number: "32145698",
            email: "Email",
        },
        menu: {
            eat: {
                breakfast: [
                    {
                        id: 2,
                        name: "Omlet",
                        available: true,
                        price: 10,
                        img: "https://media.istockphoto.com/photos/breakfast-with-bacon-eggs-pancakes-and-toast-picture-id533645537?k=20&m=533645537&s=612x612&w=0&h=KJXCpAo9XQvMI_djcnRMSsz_Y7OGS6z3-8VThxWyR0Q=",
                    },
                    {
                        id: 3,
                        name: "Nutella",
                        available: true,
                        price: 7,
                        img: "https://upload.wikimedia.org/wikipedia/commons/5/55/Nutella_bread_12-2015.jpg",
                    },
                    {
                        id: 4,
                        name: "Eggs",
                        available: true,
                        price: 5,
                        img: "https://static.fanpage.it/wp-content/uploads/sites/22/2019/07/boiled-egg-1200x900.jpg",
                    },
                ],
                lunch: [
                    {
                        id: 2,
                        name: "Omlet",
                        available: true,
                        price: 10,
                        img: "https://static.fanpage.it/wp-content/uploads/sites/22/2019/07/boiled-egg-1200x900.jpg",
                    },
                    {
                        id: 3,
                        name: "Nutella",
                        available: true,
                        price: 7,
                        img: "https://static.fanpage.it/wp-content/uploads/sites/22/2019/07/boiled-egg-1200x900.jpg",
                    },
                    {
                        id: 4,
                        name: "Eggs",
                        available: true,
                        price: 5,
                        img: "https://static.fanpage.it/wp-content/uploads/sites/22/2019/07/boiled-egg-1200x900.jpg",
                    },
                ],
                dinner: [
                    {
                        id: 2,
                        name: "Omlet",
                        available: true,
                        price: 10,
                        img: "https://media.istockphoto.com/photos/breakfast-with-bacon-eggs-pancakes-and-toast-picture-id533645537?k=20&m=533645537&s=612x612&w=0&h=KJXCpAo9XQvMI_djcnRMSsz_Y7OGS6z3-8VThxWyR0Q=",
                    },
                    {
                        id: 3,
                        name: "Nutella",
                        available: true,
                        price: 7,
                        img: "https://media.istockphoto.com/photos/breakfast-with-bacon-eggs-pancakes-and-toast-picture-id533645537?k=20&m=533645537&s=612x612&w=0&h=KJXCpAo9XQvMI_djcnRMSsz_Y7OGS6z3-8VThxWyR0Q=",
                    },
                    {
                        id: 4,
                        name: "Eggs",
                        available: true,
                        price: 5,
                        img: "https://media.istockphoto.com/photos/breakfast-with-bacon-eggs-pancakes-and-toast-picture-id533645537?k=20&m=533645537&s=612x612&w=0&h=KJXCpAo9XQvMI_djcnRMSsz_Y7OGS6z3-8VThxWyR0Q=",
                    },
                ],
            },
            drink: {
                morning: [
                    {
                        id: 2,
                        name: "coffee",
                        available: true,
                        price: 10,
                        img: "https://www.alco.moscow/photo/photo12183.jpeg",
                    },
                    {
                        id: 3,
                        name: "Juice",
                        available: true,
                        price: 7,
                        img: "https://www.alco.moscow/photo/photo12183.jpeg",
                    },
                    {
                        id: 4,
                        name: "Espresso",
                        available: true,
                        price: 5,
                        img: "https://www.alco.moscow/photo/photo12183.jpeg",
                    },
                ],
                afternoon: [
                    {
                        id: 2,
                        name: "Espresso",
                        available: true,
                        price: 10,
                        img: "https://www.alco.moscow/photo/photo12183.jpeg",
                    },
                    {
                        id: 3,
                        name: "NesCoffee",
                        available: true,
                        price: 7,
                        img: "https://www.alco.moscow/photo/photo12183.jpeg",
                    },
                    {
                        id: 4,
                        name: "Juice",
                        available: true,
                        price: 5,
                        img: "https://www.alco.moscow/photo/photo12183.jpeg",
                    },
                ],
                evening: [
                    {
                        id: 2,
                        name: "Beer",
                        available: true,
                        price: 10,
                        img: "https://www.alco.moscow/photo/photo12183.jpeg",
                    },
                    {
                        id: 3,
                        name: "wine",
                        available: true,
                        price: 7,
                        img: "https://www.alco.moscow/photo/photo12183.jpeg",
                    },
                    {
                        id: 4,
                        name: "Coctail",
                        available: true,
                        price: 5,
                        img: "https://www.alco.moscow/photo/photo12183.jpeg",
                    },
                ],
                night: [
                    {
                        id: 2,
                        name: "Wine",
                        available: true,
                        price: 10,
                        img: "https://www.alco.moscow/photo/photo12183.jpeg",
                    },
                    {
                        id: 3,
                        name: "Beer",
                        available: true,
                        price: 7,
                        img: "https://www.alco.moscow/photo/photo12183.jpeg",
                    },
                    {
                        id: 4,
                        name: "Vodka",
                        available: true,
                        price: 5,
                        img: "https://www.alco.moscow/photo/photo12183.jpeg",
                    },
                ],
            },
        },
    },
    {
        id: 2,
        name: "Italian Food Service",
        img: [
            "https://www.sortiraparis.com/images/80/91874/582754-photos-le-cafe-de-l-homme.jpg",
            "https://vistapointe.net/images/restaurant-3.jpg",
            "https://www.shilla.net/images/contents/dining/FRC/R00000019XVP_EN.jpg",
            "https://cdn.vox-cdn.com/thumbor/wuDWh1y6HHfzTUtYBPKAzBU4wTk=/0x0:1920x1280/1200x900/filters:focal(807x487:1113x793)/cdn.vox-cdn.com/uploads/chorus_image/image/58248869/Sooki_and_Mimi_Bar_and_room_cr_Jes_Lahay.97.jpg",
            "https://images.unsplash.com/photo-1552566626-52f8b828add9?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8N3x8cmVzdGF1cmFudHxlbnwwfHwwfHw%3D&w=1000&q=80",
        ],
        location: "123654 78546",
        street: "Saryan 4/2",
        country: "Armenia",
        city: "Yerevan",
        contact: {
            number: "32145698",
            email: "Email",
        },
        menu: {
            eat: {
                breakfast: [
                    {
                        id: 2,
                        name: "Omlet",
                        available: true,
                        price: 10,
                        img: "https://media.istockphoto.com/photos/breakfast-with-bacon-eggs-pancakes-and-toast-picture-id533645537?k=20&m=533645537&s=612x612&w=0&h=KJXCpAo9XQvMI_djcnRMSsz_Y7OGS6z3-8VThxWyR0Q=",
                    },
                    {
                        id: 3,
                        name: "Nutella",
                        available: true,
                        price: 7,
                        img: "https://upload.wikimedia.org/wikipedia/commons/5/55/Nutella_bread_12-2015.jpg",
                    },
                    {
                        id: 4,
                        name: "Eggs",
                        available: true,
                        price: 5,
                        img: "https://static.fanpage.it/wp-content/uploads/sites/22/2019/07/boiled-egg-1200x900.jpg",
                    },
                ],
                lunch: [
                    {
                        id: 2,
                        name: "Omlet",
                        available: true,
                        price: 10,
                        img: "https://static.fanpage.it/wp-content/uploads/sites/22/2019/07/boiled-egg-1200x900.jpg",
                    },
                    {
                        id: 3,
                        name: "Nutella",
                        available: true,
                        price: 7,
                        img: "https://static.fanpage.it/wp-content/uploads/sites/22/2019/07/boiled-egg-1200x900.jpg",
                    },
                    {
                        id: 4,
                        name: "Eggs",
                        available: true,
                        price: 5,
                        img: "https://static.fanpage.it/wp-content/uploads/sites/22/2019/07/boiled-egg-1200x900.jpg",
                    },
                ],
                dinner: [
                    {
                        id: 2,
                        name: "Omlet",
                        available: true,
                        price: 10,
                        img: "https://media.istockphoto.com/photos/breakfast-with-bacon-eggs-pancakes-and-toast-picture-id533645537?k=20&m=533645537&s=612x612&w=0&h=KJXCpAo9XQvMI_djcnRMSsz_Y7OGS6z3-8VThxWyR0Q=",
                    },
                    {
                        id: 3,
                        name: "Nutella",
                        available: true,
                        price: 7,
                        img: "https://media.istockphoto.com/photos/breakfast-with-bacon-eggs-pancakes-and-toast-picture-id533645537?k=20&m=533645537&s=612x612&w=0&h=KJXCpAo9XQvMI_djcnRMSsz_Y7OGS6z3-8VThxWyR0Q=",
                    },
                    {
                        id: 4,
                        name: "Eggs",
                        available: true,
                        price: 5,
                        img: "https://media.istockphoto.com/photos/breakfast-with-bacon-eggs-pancakes-and-toast-picture-id533645537?k=20&m=533645537&s=612x612&w=0&h=KJXCpAo9XQvMI_djcnRMSsz_Y7OGS6z3-8VThxWyR0Q=",
                    },
                ],
            },
            drink: {
                morning: [
                    {
                        id: 2,
                        name: "coffee",
                        available: true,
                        price: 10,
                        img: "https://www.alco.moscow/photo/photo12183.jpeg",
                    },
                    {
                        id: 3,
                        name: "Juice",
                        available: true,
                        price: 7,
                        img: "https://www.alco.moscow/photo/photo12183.jpeg",
                    },
                    {
                        id: 4,
                        name: "Espresso",
                        available: true,
                        price: 5,
                        img: "https://www.alco.moscow/photo/photo12183.jpeg",
                    },
                ],
                afternoon: [
                    {
                        id: 2,
                        name: "Espresso",
                        available: true,
                        price: 10,
                        img: "https://www.alco.moscow/photo/photo12183.jpeg",
                    },
                    {
                        id: 3,
                        name: "NesCoffee",
                        available: true,
                        price: 7,
                        img: "https://www.alco.moscow/photo/photo12183.jpeg",
                    },
                    {
                        id: 4,
                        name: "Juice",
                        available: true,
                        price: 5,
                        img: "https://www.alco.moscow/photo/photo12183.jpeg",
                    },
                ],
                evening: [
                    {
                        id: 2,
                        name: "Beer",
                        available: true,
                        price: 10,
                        img: "https://www.alco.moscow/photo/photo12183.jpeg",
                    },
                    {
                        id: 3,
                        name: "wine",
                        available: true,
                        price: 7,
                        img: "https://www.alco.moscow/photo/photo12183.jpeg",
                    },
                    {
                        id: 4,
                        name: "Coctail",
                        available: true,
                        price: 5,
                        img: "https://www.alco.moscow/photo/photo12183.jpeg",
                    },
                ],
                night: [
                    {
                        id: 2,
                        name: "Wine",
                        available: true,
                        price: 10,
                        img: "https://www.alco.moscow/photo/photo12183.jpeg",
                    },
                    {
                        id: 3,
                        name: "Beer",
                        available: true,
                        price: 7,
                        img: "https://www.alco.moscow/photo/photo12183.jpeg",
                    },
                    {
                        id: 4,
                        name: "Vodka",
                        available: true,
                        price: 5,
                        img: "https://www.alco.moscow/photo/photo12183.jpeg",
                    },
                ],
            },
        },
    },
    {
        id: 3,
        name: "Italian Food Service",
        img: [
            "https://www.sortiraparis.com/images/80/91874/582754-photos-le-cafe-de-l-homme.jpg",
            "https://vistapointe.net/images/restaurant-3.jpg",
            "https://www.shilla.net/images/contents/dining/FRC/R00000019XVP_EN.jpg",
            "https://cdn.vox-cdn.com/thumbor/wuDWh1y6HHfzTUtYBPKAzBU4wTk=/0x0:1920x1280/1200x900/filters:focal(807x487:1113x793)/cdn.vox-cdn.com/uploads/chorus_image/image/58248869/Sooki_and_Mimi_Bar_and_room_cr_Jes_Lahay.97.jpg",
            "https://images.unsplash.com/photo-1552566626-52f8b828add9?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8N3x8cmVzdGF1cmFudHxlbnwwfHwwfHw%3D&w=1000&q=80",
        ],
        location: "123654 78546",
        street: "Saryan 4/2",
        country: "Armenia",
        city: "Yerevan",
        contact: {
            number: "32145698",
            email: "Email",
        },
        menu: {
            eat: {
                breakfast: [
                    {
                        id: 2,
                        name: "Omlet",
                        available: true,
                        price: 10,
                        img: "https://media.istockphoto.com/photos/breakfast-with-bacon-eggs-pancakes-and-toast-picture-id533645537?k=20&m=533645537&s=612x612&w=0&h=KJXCpAo9XQvMI_djcnRMSsz_Y7OGS6z3-8VThxWyR0Q=",
                    },
                    {
                        id: 3,
                        name: "Nutella",
                        available: true,
                        price: 7,
                        img: "https://upload.wikimedia.org/wikipedia/commons/5/55/Nutella_bread_12-2015.jpg",
                    },
                    {
                        id: 4,
                        name: "Eggs",
                        available: true,
                        price: 5,
                        img: "https://static.fanpage.it/wp-content/uploads/sites/22/2019/07/boiled-egg-1200x900.jpg",
                    },
                ],
                lunch: [
                    {
                        id: 2,
                        name: "Omlet",
                        available: true,
                        price: 10,
                        img: "https://static.fanpage.it/wp-content/uploads/sites/22/2019/07/boiled-egg-1200x900.jpg",
                    },
                    {
                        id: 3,
                        name: "Nutella",
                        available: true,
                        price: 7,
                        img: "https://static.fanpage.it/wp-content/uploads/sites/22/2019/07/boiled-egg-1200x900.jpg",
                    },
                    {
                        id: 4,
                        name: "Eggs",
                        available: true,
                        price: 5,
                        img: "https://static.fanpage.it/wp-content/uploads/sites/22/2019/07/boiled-egg-1200x900.jpg",
                    },
                ],
                dinner: [
                    {
                        id: 2,
                        name: "Omlet",
                        available: true,
                        price: 10,
                        img: "https://media.istockphoto.com/photos/breakfast-with-bacon-eggs-pancakes-and-toast-picture-id533645537?k=20&m=533645537&s=612x612&w=0&h=KJXCpAo9XQvMI_djcnRMSsz_Y7OGS6z3-8VThxWyR0Q=",
                    },
                    {
                        id: 3,
                        name: "Nutella",
                        available: true,
                        price: 7,
                        img: "https://media.istockphoto.com/photos/breakfast-with-bacon-eggs-pancakes-and-toast-picture-id533645537?k=20&m=533645537&s=612x612&w=0&h=KJXCpAo9XQvMI_djcnRMSsz_Y7OGS6z3-8VThxWyR0Q=",
                    },
                    {
                        id: 4,
                        name: "Eggs",
                        available: true,
                        price: 5,
                        img: "https://media.istockphoto.com/photos/breakfast-with-bacon-eggs-pancakes-and-toast-picture-id533645537?k=20&m=533645537&s=612x612&w=0&h=KJXCpAo9XQvMI_djcnRMSsz_Y7OGS6z3-8VThxWyR0Q=",
                    },
                ],
            },
            drink: {
                morning: [
                    {
                        id: 2,
                        name: "coffee",
                        available: true,
                        price: 10,
                        img: "https://www.alco.moscow/photo/photo12183.jpeg",
                    },
                    {
                        id: 3,
                        name: "Juice",
                        available: true,
                        price: 7,
                        img: "https://www.alco.moscow/photo/photo12183.jpeg",
                    },
                    {
                        id: 4,
                        name: "Espresso",
                        available: true,
                        price: 5,
                        img: "https://www.alco.moscow/photo/photo12183.jpeg",
                    },
                ],
                afternoon: [
                    {
                        id: 2,
                        name: "Espresso",
                        available: true,
                        price: 10,
                        img: "https://www.alco.moscow/photo/photo12183.jpeg",
                    },
                    {
                        id: 3,
                        name: "NesCoffee",
                        available: true,
                        price: 7,
                        img: "https://www.alco.moscow/photo/photo12183.jpeg",
                    },
                    {
                        id: 4,
                        name: "Juice",
                        available: true,
                        price: 5,
                        img: "https://www.alco.moscow/photo/photo12183.jpeg",
                    },
                ],
                evening: [
                    {
                        id: 2,
                        name: "Beer",
                        available: true,
                        price: 10,
                        img: "https://www.alco.moscow/photo/photo12183.jpeg",
                    },
                    {
                        id: 3,
                        name: "wine",
                        available: true,
                        price: 7,
                        img: "https://www.alco.moscow/photo/photo12183.jpeg",
                    },
                    {
                        id: 4,
                        name: "Coctail",
                        available: true,
                        price: 5,
                        img: "https://www.alco.moscow/photo/photo12183.jpeg",
                    },
                ],
                night: [
                    {
                        id: 2,
                        name: "Wine",
                        available: true,
                        price: 10,
                        img: "https://www.alco.moscow/photo/photo12183.jpeg",
                    },
                    {
                        id: 3,
                        name: "Beer",
                        available: true,
                        price: 7,
                        img: "https://www.alco.moscow/photo/photo12183.jpeg",
                    },
                    {
                        id: 4,
                        name: "Vodka",
                        available: true,
                        price: 5,
                        img: "https://www.alco.moscow/photo/photo12183.jpeg",
                    },
                ],
            },
        },
    },
    {
        id: 4,
        name: "Italian Food Service",
        img: [
            "https://www.sortiraparis.com/images/80/91874/582754-photos-le-cafe-de-l-homme.jpg",
            "https://vistapointe.net/images/restaurant-3.jpg",
            "https://www.shilla.net/images/contents/dining/FRC/R00000019XVP_EN.jpg",
            "https://cdn.vox-cdn.com/thumbor/wuDWh1y6HHfzTUtYBPKAzBU4wTk=/0x0:1920x1280/1200x900/filters:focal(807x487:1113x793)/cdn.vox-cdn.com/uploads/chorus_image/image/58248869/Sooki_and_Mimi_Bar_and_room_cr_Jes_Lahay.97.jpg",
            "https://images.unsplash.com/photo-1552566626-52f8b828add9?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8N3x8cmVzdGF1cmFudHxlbnwwfHwwfHw%3D&w=1000&q=80",
        ],
        location: "123654 78546",
        street: "Saryan 4/2",
        country: "Armenia",
        city: "Yerevan",
        contact: {
            number: "32145698",
            email: "Email",
        },
        menu: {
            eat: {
                breakfast: [
                    {
                        id: 2,
                        name: "Omlet",
                        available: true,
                        price: 10,
                        img: "https://media.istockphoto.com/photos/breakfast-with-bacon-eggs-pancakes-and-toast-picture-id533645537?k=20&m=533645537&s=612x612&w=0&h=KJXCpAo9XQvMI_djcnRMSsz_Y7OGS6z3-8VThxWyR0Q=",
                    },
                    {
                        id: 3,
                        name: "Nutella",
                        available: true,
                        price: 7,
                        img: "https://upload.wikimedia.org/wikipedia/commons/5/55/Nutella_bread_12-2015.jpg",
                    },
                    {
                        id: 4,
                        name: "Eggs",
                        available: true,
                        price: 5,
                        img: "https://static.fanpage.it/wp-content/uploads/sites/22/2019/07/boiled-egg-1200x900.jpg",
                    },
                ],
                lunch: [
                    {
                        id: 2,
                        name: "Omlet",
                        available: true,
                        price: 10,
                        img: "https://static.fanpage.it/wp-content/uploads/sites/22/2019/07/boiled-egg-1200x900.jpg",
                    },
                    {
                        id: 3,
                        name: "Nutella",
                        available: true,
                        price: 7,
                        img: "https://static.fanpage.it/wp-content/uploads/sites/22/2019/07/boiled-egg-1200x900.jpg",
                    },
                    {
                        id: 4,
                        name: "Eggs",
                        available: true,
                        price: 5,
                        img: "https://static.fanpage.it/wp-content/uploads/sites/22/2019/07/boiled-egg-1200x900.jpg",
                    },
                ],
                dinner: [
                    {
                        id: 2,
                        name: "Omlet",
                        available: true,
                        price: 10,
                        img: "https://media.istockphoto.com/photos/breakfast-with-bacon-eggs-pancakes-and-toast-picture-id533645537?k=20&m=533645537&s=612x612&w=0&h=KJXCpAo9XQvMI_djcnRMSsz_Y7OGS6z3-8VThxWyR0Q=",
                    },
                    {
                        id: 3,
                        name: "Nutella",
                        available: true,
                        price: 7,
                        img: "https://media.istockphoto.com/photos/breakfast-with-bacon-eggs-pancakes-and-toast-picture-id533645537?k=20&m=533645537&s=612x612&w=0&h=KJXCpAo9XQvMI_djcnRMSsz_Y7OGS6z3-8VThxWyR0Q=",
                    },
                    {
                        id: 4,
                        name: "Eggs",
                        available: true,
                        price: 5,
                        img: "https://media.istockphoto.com/photos/breakfast-with-bacon-eggs-pancakes-and-toast-picture-id533645537?k=20&m=533645537&s=612x612&w=0&h=KJXCpAo9XQvMI_djcnRMSsz_Y7OGS6z3-8VThxWyR0Q=",
                    },
                ],
            },
            drink: {
                morning: [
                    {
                        id: 2,
                        name: "coffee",
                        available: true,
                        price: 10,
                        img: "https://www.alco.moscow/photo/photo12183.jpeg",
                    },
                    {
                        id: 3,
                        name: "Juice",
                        available: true,
                        price: 7,
                        img: "https://www.alco.moscow/photo/photo12183.jpeg",
                    },
                    {
                        id: 4,
                        name: "Espresso",
                        available: true,
                        price: 5,
                        img: "https://www.alco.moscow/photo/photo12183.jpeg",
                    },
                ],
                afternoon: [
                    {
                        id: 2,
                        name: "Espresso",
                        available: true,
                        price: 10,
                        img: "https://www.alco.moscow/photo/photo12183.jpeg",
                    },
                    {
                        id: 3,
                        name: "NesCoffee",
                        available: true,
                        price: 7,
                        img: "https://www.alco.moscow/photo/photo12183.jpeg",
                    },
                    {
                        id: 4,
                        name: "Juice",
                        available: true,
                        price: 5,
                        img: "https://www.alco.moscow/photo/photo12183.jpeg",
                    },
                ],
                evening: [
                    {
                        id: 2,
                        name: "Beer",
                        available: true,
                        price: 10,
                        img: "https://www.alco.moscow/photo/photo12183.jpeg",
                    },
                    {
                        id: 3,
                        name: "wine",
                        available: true,
                        price: 7,
                        img: "https://www.alco.moscow/photo/photo12183.jpeg",
                    },
                    {
                        id: 4,
                        name: "Coctail",
                        available: true,
                        price: 5,
                        img: "https://www.alco.moscow/photo/photo12183.jpeg",
                    },
                ],
                night: [
                    {
                        id: 2,
                        name: "Wine",
                        available: true,
                        price: 10,
                        img: "https://www.alco.moscow/photo/photo12183.jpeg",
                    },
                    {
                        id: 3,
                        name: "Beer",
                        available: true,
                        price: 7,
                        img: "https://www.alco.moscow/photo/photo12183.jpeg",
                    },
                    {
                        id: 4,
                        name: "Vodka",
                        available: true,
                        price: 5,
                        img: "https://www.alco.moscow/photo/photo12183.jpeg",
                    },
                ],
            },
        },
    },
    {
        id: 5,
        name: "Italian Food Service",
        img: [
            "https://www.sortiraparis.com/images/80/91874/582754-photos-le-cafe-de-l-homme.jpg",
            "https://vistapointe.net/images/restaurant-3.jpg",
            "https://www.shilla.net/images/contents/dining/FRC/R00000019XVP_EN.jpg",
            "https://cdn.vox-cdn.com/thumbor/wuDWh1y6HHfzTUtYBPKAzBU4wTk=/0x0:1920x1280/1200x900/filters:focal(807x487:1113x793)/cdn.vox-cdn.com/uploads/chorus_image/image/58248869/Sooki_and_Mimi_Bar_and_room_cr_Jes_Lahay.97.jpg",
            "https://images.unsplash.com/photo-1552566626-52f8b828add9?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8N3x8cmVzdGF1cmFudHxlbnwwfHwwfHw%3D&w=1000&q=80",
        ],
        location: "123654 78546",
        street: "Saryan 4/2",
        country: "Armenia",
        city: "Yerevan",
        contact: {
            number: "32145698",
            email: "Email",
        },
        menu: {
            eat: {
                breakfast: [
                    {
                        id: 2,
                        name: "Omlet",
                        available: true,
                        price: 10,
                        img: "https://media.istockphoto.com/photos/breakfast-with-bacon-eggs-pancakes-and-toast-picture-id533645537?k=20&m=533645537&s=612x612&w=0&h=KJXCpAo9XQvMI_djcnRMSsz_Y7OGS6z3-8VThxWyR0Q=",
                    },
                    {
                        id: 3,
                        name: "Nutella",
                        available: true,
                        price: 7,
                        img: "https://upload.wikimedia.org/wikipedia/commons/5/55/Nutella_bread_12-2015.jpg",
                    },
                    {
                        id: 4,
                        name: "Eggs",
                        available: true,
                        price: 5,
                        img: "https://static.fanpage.it/wp-content/uploads/sites/22/2019/07/boiled-egg-1200x900.jpg",
                    },
                ],
                lunch: [
                    {
                        id: 2,
                        name: "Omlet",
                        available: true,
                        price: 10,
                        img: "https://static.fanpage.it/wp-content/uploads/sites/22/2019/07/boiled-egg-1200x900.jpg",
                    },
                    {
                        id: 3,
                        name: "Nutella",
                        available: true,
                        price: 7,
                        img: "https://static.fanpage.it/wp-content/uploads/sites/22/2019/07/boiled-egg-1200x900.jpg",
                    },
                    {
                        id: 4,
                        name: "Eggs",
                        available: true,
                        price: 5,
                        img: "https://static.fanpage.it/wp-content/uploads/sites/22/2019/07/boiled-egg-1200x900.jpg",
                    },
                ],
                dinner: [
                    {
                        id: 2,
                        name: "Omlet",
                        available: true,
                        price: 10,
                        img: "https://media.istockphoto.com/photos/breakfast-with-bacon-eggs-pancakes-and-toast-picture-id533645537?k=20&m=533645537&s=612x612&w=0&h=KJXCpAo9XQvMI_djcnRMSsz_Y7OGS6z3-8VThxWyR0Q=",
                    },
                    {
                        id: 3,
                        name: "Nutella",
                        available: true,
                        price: 7,
                        img: "https://media.istockphoto.com/photos/breakfast-with-bacon-eggs-pancakes-and-toast-picture-id533645537?k=20&m=533645537&s=612x612&w=0&h=KJXCpAo9XQvMI_djcnRMSsz_Y7OGS6z3-8VThxWyR0Q=",
                    },
                    {
                        id: 4,
                        name: "Eggs",
                        available: true,
                        price: 5,
                        img: "https://media.istockphoto.com/photos/breakfast-with-bacon-eggs-pancakes-and-toast-picture-id533645537?k=20&m=533645537&s=612x612&w=0&h=KJXCpAo9XQvMI_djcnRMSsz_Y7OGS6z3-8VThxWyR0Q=",
                    },
                ],
            },
            drink: {
                morning: [
                    {
                        id: 2,
                        name: "coffee",
                        available: true,
                        price: 10,
                        img: "https://www.alco.moscow/photo/photo12183.jpeg",
                    },
                    {
                        id: 3,
                        name: "Juice",
                        available: true,
                        price: 7,
                        img: "https://www.alco.moscow/photo/photo12183.jpeg",
                    },
                    {
                        id: 4,
                        name: "Espresso",
                        available: true,
                        price: 5,
                        img: "https://www.alco.moscow/photo/photo12183.jpeg",
                    },
                ],
                afternoon: [
                    {
                        id: 2,
                        name: "Espresso",
                        available: true,
                        price: 10,
                        img: "https://www.alco.moscow/photo/photo12183.jpeg",
                    },
                    {
                        id: 3,
                        name: "NesCoffee",
                        available: true,
                        price: 7,
                        img: "https://www.alco.moscow/photo/photo12183.jpeg",
                    },
                    {
                        id: 4,
                        name: "Juice",
                        available: true,
                        price: 5,
                        img: "https://www.alco.moscow/photo/photo12183.jpeg",
                    },
                ],
                evening: [
                    {
                        id: 2,
                        name: "Beer",
                        available: true,
                        price: 10,
                        img: "https://www.alco.moscow/photo/photo12183.jpeg",
                    },
                    {
                        id: 3,
                        name: "wine",
                        available: true,
                        price: 7,
                        img: "https://www.alco.moscow/photo/photo12183.jpeg",
                    },
                    {
                        id: 4,
                        name: "Coctail",
                        available: true,
                        price: 5,
                        img: "https://www.alco.moscow/photo/photo12183.jpeg",
                    },
                ],
                night: [
                    {
                        id: 2,
                        name: "Wine",
                        available: true,
                        price: 10,
                        img: "https://www.alco.moscow/photo/photo12183.jpeg",
                    },
                    {
                        id: 3,
                        name: "Beer",
                        available: true,
                        price: 7,
                        img: "https://www.alco.moscow/photo/photo12183.jpeg",
                    },
                    {
                        id: 4,
                        name: "Vodka",
                        available: true,
                        price: 5,
                        img: "https://www.alco.moscow/photo/photo12183.jpeg",
                    },
                ],
            },
        },
    },
    {
        id: 6,
        name: "Italian Food Service",
        img: [
            "https://www.sortiraparis.com/images/80/91874/582754-photos-le-cafe-de-l-homme.jpg",
            "https://vistapointe.net/images/restaurant-3.jpg",
            "https://www.shilla.net/images/contents/dining/FRC/R00000019XVP_EN.jpg",
            "https://cdn.vox-cdn.com/thumbor/wuDWh1y6HHfzTUtYBPKAzBU4wTk=/0x0:1920x1280/1200x900/filters:focal(807x487:1113x793)/cdn.vox-cdn.com/uploads/chorus_image/image/58248869/Sooki_and_Mimi_Bar_and_room_cr_Jes_Lahay.97.jpg",
            "https://images.unsplash.com/photo-1552566626-52f8b828add9?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8N3x8cmVzdGF1cmFudHxlbnwwfHwwfHw%3D&w=1000&q=80",
        ],
        location: "123654 78546",
        street: "Saryan 4/2",
        country: "Armenia",
        city: "Yerevan",
        contact: {
            number: "32145698",
            email: "Email",
        },
        menu: {
            eat: {
                breakfast: [
                    {
                        id: 2,
                        name: "Omlet",
                        available: true,
                        price: 10,
                        img: "https://media.istockphoto.com/photos/breakfast-with-bacon-eggs-pancakes-and-toast-picture-id533645537?k=20&m=533645537&s=612x612&w=0&h=KJXCpAo9XQvMI_djcnRMSsz_Y7OGS6z3-8VThxWyR0Q=",
                    },
                    {
                        id: 3,
                        name: "Nutella",
                        available: true,
                        price: 7,
                        img: "https://upload.wikimedia.org/wikipedia/commons/5/55/Nutella_bread_12-2015.jpg",
                    },
                    {
                        id: 4,
                        name: "Eggs",
                        available: true,
                        price: 5,
                        img: "https://static.fanpage.it/wp-content/uploads/sites/22/2019/07/boiled-egg-1200x900.jpg",
                    },
                ],
                lunch: [
                    {
                        id: 2,
                        name: "Omlet",
                        available: true,
                        price: 10,
                        img: "https://static.fanpage.it/wp-content/uploads/sites/22/2019/07/boiled-egg-1200x900.jpg",
                    },
                    {
                        id: 3,
                        name: "Nutella",
                        available: true,
                        price: 7,
                        img: "https://static.fanpage.it/wp-content/uploads/sites/22/2019/07/boiled-egg-1200x900.jpg",
                    },
                    {
                        id: 4,
                        name: "Eggs",
                        available: true,
                        price: 5,
                        img: "https://static.fanpage.it/wp-content/uploads/sites/22/2019/07/boiled-egg-1200x900.jpg",
                    },
                ],
                dinner: [
                    {
                        id: 2,
                        name: "Omlet",
                        available: true,
                        price: 10,
                        img: "https://media.istockphoto.com/photos/breakfast-with-bacon-eggs-pancakes-and-toast-picture-id533645537?k=20&m=533645537&s=612x612&w=0&h=KJXCpAo9XQvMI_djcnRMSsz_Y7OGS6z3-8VThxWyR0Q=",
                    },
                    {
                        id: 3,
                        name: "Nutella",
                        available: true,
                        price: 7,
                        img: "https://media.istockphoto.com/photos/breakfast-with-bacon-eggs-pancakes-and-toast-picture-id533645537?k=20&m=533645537&s=612x612&w=0&h=KJXCpAo9XQvMI_djcnRMSsz_Y7OGS6z3-8VThxWyR0Q=",
                    },
                    {
                        id: 4,
                        name: "Eggs",
                        available: true,
                        price: 5,
                        img: "https://media.istockphoto.com/photos/breakfast-with-bacon-eggs-pancakes-and-toast-picture-id533645537?k=20&m=533645537&s=612x612&w=0&h=KJXCpAo9XQvMI_djcnRMSsz_Y7OGS6z3-8VThxWyR0Q=",
                    },
                ],
            },
            drink: {
                morning: [
                    {
                        id: 2,
                        name: "coffee",
                        available: true,
                        price: 10,
                        img: "https://www.alco.moscow/photo/photo12183.jpeg",
                    },
                    {
                        id: 3,
                        name: "Juice",
                        available: true,
                        price: 7,
                        img: "https://www.alco.moscow/photo/photo12183.jpeg",
                    },
                    {
                        id: 4,
                        name: "Espresso",
                        available: true,
                        price: 5,
                        img: "https://www.alco.moscow/photo/photo12183.jpeg",
                    },
                ],
                afternoon: [
                    {
                        id: 2,
                        name: "Espresso",
                        available: true,
                        price: 10,
                        img: "https://www.alco.moscow/photo/photo12183.jpeg",
                    },
                    {
                        id: 3,
                        name: "NesCoffee",
                        available: true,
                        price: 7,
                        img: "https://www.alco.moscow/photo/photo12183.jpeg",
                    },
                    {
                        id: 4,
                        name: "Juice",
                        available: true,
                        price: 5,
                        img: "https://www.alco.moscow/photo/photo12183.jpeg",
                    },
                ],
                evening: [
                    {
                        id: 2,
                        name: "Beer",
                        available: true,
                        price: 10,
                        img: "https://www.alco.moscow/photo/photo12183.jpeg",
                    },
                    {
                        id: 3,
                        name: "wine",
                        available: true,
                        price: 7,
                        img: "https://www.alco.moscow/photo/photo12183.jpeg",
                    },
                    {
                        id: 4,
                        name: "Coctail",
                        available: true,
                        price: 5,
                        img: "https://www.alco.moscow/photo/photo12183.jpeg",
                    },
                ],
                night: [
                    {
                        id: 2,
                        name: "Wine",
                        available: true,
                        price: 10,
                        img: "https://www.alco.moscow/photo/photo12183.jpeg",
                    },
                    {
                        id: 3,
                        name: "Beer",
                        available: true,
                        price: 7,
                        img: "https://www.alco.moscow/photo/photo12183.jpeg",
                    },
                    {
                        id: 4,
                        name: "Vodka",
                        available: true,
                        price: 5,
                        img: "https://www.alco.moscow/photo/photo12183.jpeg",
                    },
                ],
            },
        },
    },
];
